# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergedGUIrenamed.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 700)
        Form.setMinimumSize(QtCore.QSize(960, 700))
        Form.setMaximumSize(QtCore.QSize(960, 700))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.sqli_run = QtWidgets.QPushButton(self.tab)
        self.sqli_run.setGeometry(QtCore.QRect(750, 280, 150, 41))
        self.sqli_run.setObjectName("sqli_run")
        self.sqli_result = QtWidgets.QTextEdit(self.tab)
        self.sqli_result.setGeometry(QtCore.QRect(490, 40, 421, 211))
        self.sqli_result.setObjectName("sqli_result")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 181, 21))
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(490, 20, 181, 21))
        self.label_13.setObjectName("label_13")
        self.sqli_url = QtWidgets.QTextEdit(self.tab)
        self.sqli_url.setGeometry(QtCore.QRect(60, 280, 680, 25))
        self.sqli_url.setObjectName("sqli_url")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(10, 320, 181, 21))
        self.label_14.setObjectName("label_14")
        self.sqli_log = QtWidgets.QTextEdit(self.tab)
        self.sqli_log.setGeometry(QtCore.QRect(10, 350, 900, 280))
        self.sqli_log.setObjectName("sqli_log")
        self.sqli_vulinfo = QtWidgets.QTextEdit(self.tab)
        self.sqli_vulinfo.setGeometry(QtCore.QRect(20, 40, 421, 211))
        self.sqli_vulinfo.setObjectName("sqli_vulinfo")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setGeometry(QtCore.QRect(490, 20, 181, 21))
        self.label_65.setObjectName("label_65")
        self.lfi_result = QtWidgets.QTextEdit(self.tab_3)
        self.lfi_result.setGeometry(QtCore.QRect(490, 40, 421, 211))
        self.lfi_result.setObjectName("lfi_result")
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        self.label_66.setGeometry(QtCore.QRect(10, 280, 181, 21))
        self.label_66.setObjectName("label_66")
        self.lfi_target = QtWidgets.QTextEdit(self.tab_3)
        self.lfi_target.setGeometry(QtCore.QRect(60, 280, 680, 25))
        self.lfi_target.setObjectName("lfi_target")
        self.llfi_run = QtWidgets.QPushButton(self.tab_3)
        self.llfi_run.setGeometry(QtCore.QRect(750, 280, 150, 41))
        self.llfi_run.setObjectName("llfi_run")
        self.label_67 = QtWidgets.QLabel(self.tab_3)
        self.label_67.setGeometry(QtCore.QRect(10, 320, 181, 21))
        self.label_67.setObjectName("label_67")
        self.lfi_log = QtWidgets.QTextEdit(self.tab_3)
        self.lfi_log.setGeometry(QtCore.QRect(10, 350, 900, 280))
        self.lfi_log.setObjectName("lfi_log")
        self.lfi_vulinfo = QtWidgets.QTextEdit(self.tab_3)
        self.lfi_vulinfo.setGeometry(QtCore.QRect(20, 40, 421, 211))
        self.lfi_vulinfo.setObjectName("lfi_vulinfo")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_68 = QtWidgets.QLabel(self.tab_2)
        self.label_68.setGeometry(QtCore.QRect(490, 20, 181, 21))
        self.label_68.setObjectName("label_68")
        self.xss_result = QtWidgets.QTextEdit(self.tab_2)
        self.xss_result.setGeometry(QtCore.QRect(490, 40, 421, 211))
        self.xss_result.setObjectName("xss_result")
        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(10, 280, 181, 21))
        self.label_69.setObjectName("label_69")
        self.xss_target = QtWidgets.QTextEdit(self.tab_2)
        self.xss_target.setGeometry(QtCore.QRect(60, 280, 680, 25))
        self.xss_target.setObjectName("xss_target")
        self.xss_run = QtWidgets.QPushButton(self.tab_2)
        self.xss_run.setGeometry(QtCore.QRect(750, 280, 150, 41))
        self.xss_run.setObjectName("xss_run")
        self.label_70 = QtWidgets.QLabel(self.tab_2)
        self.label_70.setGeometry(QtCore.QRect(10, 320, 181, 21))
        self.label_70.setObjectName("label_70")
        self.xss_log = QtWidgets.QTextEdit(self.tab_2)
        self.xss_log.setGeometry(QtCore.QRect(10, 350, 900, 280))
        self.xss_log.setObjectName("xss_log")
        self.xss_vulinfo = QtWidgets.QTextEdit(self.tab_2)
        self.xss_vulinfo.setGeometry(QtCore.QRect(20, 40, 421, 211))
        self.xss_vulinfo.setObjectName("xss_vulinfo")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_71 = QtWidgets.QLabel(self.tab_4)
        self.label_71.setGeometry(QtCore.QRect(490, 20, 181, 21))
        self.label_71.setObjectName("label_71")
        self.brute_result = QtWidgets.QTextEdit(self.tab_4)
        self.brute_result.setGeometry(QtCore.QRect(490, 40, 421, 211))
        self.brute_result.setObjectName("brute_result")
        self.label_72 = QtWidgets.QLabel(self.tab_4)
        self.label_72.setGeometry(QtCore.QRect(20, 280, 131, 21))
        self.label_72.setObjectName("label_72")
        self.brute_pass = QtWidgets.QTextEdit(self.tab_4)
        self.brute_pass.setGeometry(QtCore.QRect(160, 340, 751, 24))
        self.brute_pass.setObjectName("brute_pass")
        self.label_73 = QtWidgets.QLabel(self.tab_4)
        self.label_73.setGeometry(QtCore.QRect(20, 310, 181, 21))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_4)
        self.label_74.setGeometry(QtCore.QRect(20, 340, 181, 21))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_4)
        self.label_75.setGeometry(QtCore.QRect(20, 400, 121, 21))
        self.label_75.setObjectName("label_75")
        self.brute_login = QtWidgets.QTextEdit(self.tab_4)
        self.brute_login.setGeometry(QtCore.QRect(160, 310, 751, 24))
        self.brute_login.setObjectName("brute_login")
        self.brute_site = QtWidgets.QTextEdit(self.tab_4)
        self.brute_site.setGeometry(QtCore.QRect(160, 280, 751, 24))
        self.brute_site.setObjectName("brute_site")
        self.brute_path_to_password = QtWidgets.QTextEdit(self.tab_4)
        self.brute_path_to_password.setGeometry(QtCore.QRect(160, 400, 591, 24))
        self.brute_path_to_password.setObjectName("brute_path_to_password")
        self.label_76 = QtWidgets.QLabel(self.tab_4)
        self.label_76.setGeometry(QtCore.QRect(20, 370, 131, 21))
        self.label_76.setObjectName("label_76")
        self.brute_selectfile = QtWidgets.QPushButton(self.tab_4)
        self.brute_selectfile.setGeometry(QtCore.QRect(760, 400, 150, 33))
        self.brute_selectfile.setObjectName("brute_selectfile")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(10, 460, 181, 21))
        self.label_34.setObjectName("label_34")
        self.brute_log = QtWidgets.QTextEdit(self.tab_4)
        self.brute_log.setGeometry(QtCore.QRect(10, 499, 900, 141))
        self.brute_log.setObjectName("brute_log")
        self.brute_button = QtWidgets.QTextEdit(self.tab_4)
        self.brute_button.setGeometry(QtCore.QRect(160, 370, 751, 24))
        self.brute_button.setObjectName("brute_button")
        self.brut_run = QtWidgets.QPushButton(self.tab_4)
        self.brut_run.setGeometry(QtCore.QRect(760, 450, 150, 36))
        self.brut_run.setObjectName("brut_run")
        self.prediction_report_29 = QtWidgets.QTextEdit(self.tab_4)
        self.prediction_report_29.setGeometry(QtCore.QRect(160, 430, 591, 24))
        self.prediction_report_29.setObjectName("prediction_report_29")
        self.label_77 = QtWidgets.QLabel(self.tab_4)
        self.label_77.setGeometry(QtCore.QRect(20, 430, 121, 21))
        self.label_77.setObjectName("label_77")
        self.brute_vulinfo = QtWidgets.QTextEdit(self.tab_4)
        self.brute_vulinfo.setGeometry(QtCore.QRect(20, 40, 421, 211))
        self.brute_vulinfo.setObjectName("brute_vulinfo")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SQLi Tool"))
        self.label.setText(_translate("Form", "Vurnerability info"))
        self.sqli_run.setText(_translate("Form", "RUN!"))
        self.label_7.setText(_translate("Form", "URL:"))
        self.label_13.setText(_translate("Form", "Result"))
        self.label_14.setText(_translate("Form", "LOG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "SQLi"))
        self.label_3.setText(_translate("Form", "Vurnerability info"))
        self.label_65.setText(_translate("Form", "Result"))
        self.label_66.setText(_translate("Form", "Target:"))
        self.llfi_run.setText(_translate("Form", "RUN!"))
        self.label_67.setText(_translate("Form", "LOG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "LFI"))
        self.label_5.setText(_translate("Form", "Vurnerability info"))
        self.label_68.setText(_translate("Form", "Result"))
        self.label_69.setText(_translate("Form", "Target:"))
        self.xss_run.setText(_translate("Form", "RUN!"))
        self.label_70.setText(_translate("Form", "LOG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "XSS"))
        self.label_6.setText(_translate("Form", "Vurnerability info"))
        self.label_71.setText(_translate("Form", "Result"))
        self.label_72.setText(_translate("Form", "Site"))
        self.label_73.setText(_translate("Form", "Log in selector"))
        self.label_74.setText(_translate("Form", "Pass selector"))
        self.label_75.setText(_translate("Form", "Path to passwords"))
        self.label_76.setText(_translate("Form", "Button selector"))
        self.brute_selectfile.setText(_translate("Form", "Select file"))
        self.label_34.setText(_translate("Form", "LOG"))
        self.brut_run.setText(_translate("Form", "RUN!"))
        self.label_77.setText(_translate("Form", "Username:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Brute"))
        self.tabWidget.setStyleSheet("color: rgb(119, 133, 255);")

